# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatto < Formula
  desc "Interactive VCS-based todo-list for the command-line"
  homepage "https://github.com/handlebargh/yatto"
  version "0.23.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/handlebargh/yatto/releases/download/v0.23.1/yatto_0.23.1_darwin_amd64.tar.gz"
      sha256 "02b44f04bea4069780fa85496987957d2ea7e6836294c438a131ce6b95a10a89"

      def install
        bin.install "yatto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/handlebargh/yatto/releases/download/v0.23.1/yatto_0.23.1_darwin_arm64.tar.gz"
      sha256 "3d2503a9b04c17a3f717c03d588cfb2a554b54a0b28f65602f6aae0f202db046"

      def install
        bin.install "yatto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/handlebargh/yatto/releases/download/v0.23.1/yatto_0.23.1_linux_amd64.tar.gz"
      sha256 "4c71dc1474abd663ee7ff360647ce5e85d66e0a89609284d8647da9eeb1b2ba8"
      def install
        bin.install "yatto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/handlebargh/yatto/releases/download/v0.23.1/yatto_0.23.1_linux_arm64.tar.gz"
      sha256 "23684aa37d99144274f9edb80fe620e1ac31a2885ef5d82b7e143abed052bdf7"
      def install
        bin.install "yatto"
      end
    end
  end

  def caveats
    <<~EOS
      yatto requires either Git or Jujutsu (jj) to be installed and available in your PATH.
      You can install them with:
        brew install git
      or
        brew install jj
    EOS
  end

  test do
    system "#{bin}/yatto", "version"
  end
end
