# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatto < Formula
  desc "Interactive VCS-based todo-list for the command-line"
  homepage "https://github.com/handlebargh/yatto"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/handlebargh/yatto/releases/download/v1.0.0/yatto_1.0.0_darwin_amd64.tar.gz"
      sha256 "bdedf1c88e7c0d4bd0a6c534c0730296a96f6e3634eb281acfb64ab0f02ca5a1"

      def install
        bin.install "yatto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/handlebargh/yatto/releases/download/v1.0.0/yatto_1.0.0_darwin_arm64.tar.gz"
      sha256 "dd1dd311ff4e2ef87337a2a5246854af9dcf4567b63c5c7cb6cd1b8c7bf31b43"

      def install
        bin.install "yatto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/handlebargh/yatto/releases/download/v1.0.0/yatto_1.0.0_linux_amd64.tar.gz"
      sha256 "0bb5b419e50efdbdfa154d0022c01ab779d0f5abbc3d8199ede87846c968e429"
      def install
        bin.install "yatto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/handlebargh/yatto/releases/download/v1.0.0/yatto_1.0.0_linux_arm64.tar.gz"
      sha256 "de1bcbc966e9c98c7a01bcbd04453608ba63641fe0cdfd18b57200cfdfda5eff"
      def install
        bin.install "yatto"
      end
    end
  end

  def caveats
    <<~EOS
      yatto requires either Git or Jujutsu (jj) to be installed and available in your PATH.
      You can install them with:
        brew install git
      or
        brew install jj
    EOS
  end

  test do
    system "#{bin}/yatto", "version"
  end
end
