# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yatto < Formula
  desc "Interactive version-controlled todo-list for the command-line"
  homepage "https://github.com/handlebargh/yatto"
  version "1.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/handlebargh/yatto/releases/download/v1.1.1/yatto_1.1.1_darwin_amd64.tar.gz"
      sha256 "96df2ad53c3f1a2fae7d6ea84f166f575a19c33e64064e60ae3a4962d4435b1d"

      def install
        bin.install "yatto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/handlebargh/yatto/releases/download/v1.1.1/yatto_1.1.1_darwin_arm64.tar.gz"
      sha256 "234fad1edeaac00f163d7fb50e035d2879bed3227895fc73cf13b793e9f3d8df"

      def install
        bin.install "yatto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/handlebargh/yatto/releases/download/v1.1.1/yatto_1.1.1_linux_amd64.tar.gz"
      sha256 "216d95838df67eb191a94d4654721f3693433cf3b7ad5cbcf051b1e1c8918410"
      def install
        bin.install "yatto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/handlebargh/yatto/releases/download/v1.1.1/yatto_1.1.1_linux_arm64.tar.gz"
      sha256 "ba037745259455c769efb846cfae002426c1bc43771d0e79920b6309a6e1a02a"
      def install
        bin.install "yatto"
      end
    end
  end

  def caveats
    <<~EOS
      yatto requires either Git or Jujutsu (jj) to be installed and available in your PATH.
      You can install them with:
        brew install git
      or
        brew install jj
    EOS
  end

  test do
    system "#{bin}/yatto", "version"
  end
end
