---
name: Test Formula

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Test formula
        run: |
          brew install --build-from-source ./Formula/yatto.rb
          brew test ./Formula/yatto.rb
