---
name: Test Formula

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Test formula
        run: /home/linuxbrew/.linuxbrew/bin/brew install --build-from-source Formula/myapp.rb
