---
name: Test Formula Installation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: test
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install formula
        run: |
          brew tap handlebargh/yatto
          brew install yatto
