---
name: Update Formula

on:
  push:
    tags:
      - "v*"

jobs:
  update-and-test:
    runs-on: macos-latest
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get release info
        id: release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          REVISION=$(git ls-remote https://github.com/handlebargh/yatto.git refs/tags/$TAG_NAME | cut -f1)
          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "revision=${REVISION}" >> $GITHUB_OUTPUT

      - name: Update formula
        run: |
          FORMULA_FILE="Formula/yatto.rb"

          sed -i'' -e "s|url \".*\"|url \"https://github.com/handlebargh/yatto.git\"|" $FORMULA_FILE
          sed -i'' -e "s|tag: \".*\"|tag:      \"${{ steps.release.outputs.tag_name }}\"|" $FORMULA_FILE
          sed -i'' -e "s|revision: \".*\"|revision: \"${{ steps.release.outputs.revision }}\"|" $FORMULA_FILE

          echo "Formula updated with:"
          echo "  Tag: ${{ steps.release.outputs.tag_name }}"
          echo "  Revision: ${{ steps.release.outputs.revision }}"

      - name: Test installation
        run: |
          brew tap testing/yatto file://$(pwd)
          brew install --verbose testing/yatto/yatto

      - name: Validate formula syntax
        run: |
          brew audit --strict testing/yatto/yatto

      - name: Test basic functionality
        run: |
          export PATH="$(brew --prefix)/bin:$PATH"
          yatto --version

      - name: Clean up test installation
        run: |
          brew uninstall testing/yatto/yatto

      - name: Commit updated formula
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Formula/yatto.rb

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update formula to ${{ steps.release.outputs.tag_name }}
          - Updated tag to ${{ steps.release.outputs.tag_name }}
          - Updated revision to ${{ steps.release.outputs.revision }}"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
            echo "Formula updated and pushed successfully!"
          fi
