---
name: Update Formula

on:
  push:
    tags:
      - "v*"

jobs:
  update-and-test:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Get release info
        id: release
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          TARBALL_URL="https://github.com/handlebargh/yatto/archive/refs/tags/${TAG_NAME}.tar.gz"

          echo "tag_name=${TAG_NAME}" >> $GITHUB_OUTPUT
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "tarball_url=${TARBALL_URL}" >> $GITHUB_OUTPUT

      - name: Calculate new SHA256
        id: sha
        run: |
          echo "Downloading and calculating SHA256 for ${{ steps.release.outputs.tarball_url }}"
          SHA256=$(curl -sL "${{ steps.release.outputs.tarball_url }}" | sha256sum | cut -d' ' -f1)
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
          echo "New SHA256: ${SHA256}"

      - name: Update formula
        run: |
          FORMULA_FILE="Formula/yatto.rb"

          sed -i'' -e "s|url \".*\"|url \"${{ steps.release.outputs.tarball_url }}\"|" $FORMULA_FILE
          sed -i'' -e "s|sha256 \".*\"|sha256 \"${{ steps.sha.outputs.sha256 }}\"|" $FORMULA_FILE
          sed -i'' -e "s|version \".*\"|version \"${{ steps.release.outputs.version }}\"|" $FORMULA_FILE
          sed -i'' -e "s|-X main.version=v.*\"|-X main.version=v${{ steps.release.outputs.version }}\"|" $FORMULA_FILE

          echo "Formula updated with:"
          echo "  Version: ${{ steps.release.outputs.version }}"
          echo "  URL: ${{ steps.release.outputs.tarball_url }}"
          echo "  SHA256: ${{ steps.sha.outputs.sha256 }}"

      - name: Test installation
        run: |
          echo "Testing formula installation..."
          brew tap testing/yatto file://$(pwd)
          brew install --verbose testing/yatto/yatto

      - name: Validate formula syntax
        run: |
          brew audit --strict testing/yatto/yatto

      - name: Test basic functionality
        run: |
          echo "Testing basic app functionality..."
          export PATH="$(brew --prefix)/bin:$PATH"
          yatto --version

      - name: Clean up test installation
        run: |
          brew uninstall testing/yatto/yatto

      - name: Commit updated formula
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          git add Formula/yatto.rb

          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update formula to ${{ steps.release.outputs.tag_name }}

          - Updated version to ${{ steps.release.outputs.version }}
          - Updated SHA256 to ${{ steps.sha.outputs.sha256 }}"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
            echo "Formula updated and pushed successfully!"
          fi
